# Generated by Django 4.2.16 on 2024-10-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DadoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dado', models.CharField(choices=[('nome', 'Nome'), ('cpf', 'CPF'), ('endereco', 'Endereço'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('dados_saude', 'Dados de Saúde')], max_length=50)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_pessoais', to='core.registrotratamento')),
            ],
        ),
    ]
