# Generated by Django 4.2.16 on 2024-10-08 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotratamento',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registrotratamento',
            name='departamento',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
