# Generated by Django 4.2.16 on 2024-10-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrotratamento_data_criacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotratamento',
            old_name='departamento',
            new_name='secretaria',
        ),
        migrations.RenameField(
            model_name='registrotratamento',
            old_name='tipo_registro',
            new_name='tipo_de_registro',
        ),
    ]
