# Generated by Django 4.2.16 on 2024-10-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_departamento_registrotratamento_secretaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrotratamento',
            old_name='tipo_de_registro',
            new_name='atividade_de_tratamento',
        ),
        migrations.RenameField(
            model_name='registrotratamento',
            old_name='secretaria',
            new_name='secretaria_ou_departamento',
        ),
        migrations.CreateModel(
            name='DadosSensiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_sensiveis', models.CharField(choices=[('Sim', 'Não')], max_length=50)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_sensiveis', to='core.registrotratamento')),
            ],
        ),
        migrations.CreateModel(
            name='CriancaAdolescente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crianca_adolescente', models.CharField(choices=[('Sim', 'Não')], max_length=50)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crianca_adolescente', to='core.registrotratamento')),
            ],
        ),
        migrations.CreateModel(
            name='BaseLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_legal', models.CharField(choices=[('Consentimento', 'Cumprimento de Obrigação Legal'), ('Execução de Políticas Públicas', 'Interesse Legítimo'), ('Exercício Regular de Direito em Processo Judicial/Administrativo', 'Proteção da Vida ou da Incolumidade Física do Titular')], max_length=70)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_legal', to='core.registrotratamento')),
            ],
        ),
    ]
