# Generated by Django 4.2.16 on 2024-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_tipo_de_registro_registrotratamento_atividade_de_tratamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselegal',
            name='base_legal',
            field=models.CharField(choices=[('consentimento', 'Consentimento'), ('cumprimento_obrigacao', 'Cumprimento de Obrigação Legal'), ('execucao_politicas', 'Execução de Políticas Públicas'), ('interesse_legitimo', 'Interesse Legítimo'), ('exercicio_direito', 'Exercício Regular de Direito em Processo Judicial/Administrativo'), ('protecao_vida', 'Proteção da Vida ou da Incolumidade Física do Titular')], max_length=260),
        ),
        migrations.AlterField(
            model_name='criancaadolescente',
            name='crianca_adolescente',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dadopessoal',
            name='tipo_dado',
            field=models.CharField(choices=[('nome', 'Nome'), ('cpf', 'CPF'), ('endereco', 'Endereço'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('dados_saude', 'Dados de Saúde')], max_length=200),
        ),
        migrations.AlterField(
            model_name='dadossensiveis',
            name='dados_sensiveis',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=100),
        ),
    ]
